### ISSUE TITLE
COLUMN_LOCAL_FILENAME is deprecated on Android 7.0, causes crash

### ISSUE THREAD

**Issue by mustafa-demir** [bemobi/medescope#9]
**COLUMN_LOCAL_FILENAME** is deprecated on **Android 7.0**, causes crash. 

Library needs an urgent update. 

**Details for the crash :**

Fatal Exception: java.lang.SecurityException: COLUMN_LOCAL_FILENAME is deprecated; use ContentResolver.openFileDescriptor() instead
       at android.app.DownloadManager$CursorTranslator.getString(DownloadManager.java:1499)
       at android.database.DatabaseUtils.dumpCurrentRow(DatabaseUtils.java:573)
       at android.database.DatabaseUtils.dumpCursor(DatabaseUtils.java:507)
       at android.database.DatabaseUtils.dumpCursorToString(DatabaseUtils.java:523)
       at br.com.bemobi.medescope.service.impl.DMDownloadService.getDownloadInfo(DMDownloadService.java:149)
       at br.com.bemobi.medescope.service.impl.DMIntentService.onHandleIntent(DMIntentService.java:51)
       at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:67)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by pedrocortez** [comment]
We've already did this, but we forgot to update project on github. We will do this soon. After that i will close this issue

**Comment by mustafa-demir** [comment]
Still waiting for this update. Can you please update the project as soon as possible.

**Comment by mustafa-demir** [comment]
Still waiting for this update. Can you please update the project as soon as possible. Thank you.

**Comment by kellvembarbosa** [comment]
Opa, Pedro aguardamos a atualização...

**Comment by kongsonida** [comment]
Did you fix it?

**Comment by paulocoutinhox** [comment]
If was fixed?

**Comment by amsterdatech** [comment]
Yes , it was a long ago, but merge has been postponed due to planning
issues.

I'll be fixed hopefully this week

**Comment by PedroBernils** [comment]
Is there an approximate date for when this update will go live?

**Comment by mabelEain** [comment]
Hello! I am also faced with this error. How to fix?
